# Generated by Django 5.2.4 on 2025-07-29 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_chatroom_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='room',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.DeleteModel(
            name='ChatRoom',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
